# Generated by Django 5.0.3 on 2024-03-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("cellphone", models.CharField(max_length=20)),
                ("companion_qty", models.IntegerField(default=0)),
                ("companion_names", models.CharField(max_length=100)),
                ("confirmed_1", models.BooleanField(default=False)),
                ("confirmed_2", models.BooleanField(default=False)),
                ("confirmed_3", models.BooleanField(default=False)),
            ],
        ),
    ]
